// `beat rolecheck <wav> --role <role>` — the pre-batch pass/fail screen (research 138 §3-B2,
// 140 D26). One clip, one role, one verdict per measured axis, and for every MISS the specific
// dotbeat parameter to change.
//
// WHY THIS EXISTS. Research 138 states the design rule the program has never had a way to obey:
// "every arm's clips pass their feature gates BEFORE entering a batch (never spend owner ratings
// on a clip that missed its own targets)" — owner rating time is the scarcest resource in the
// whole program. Doc 140 found `rg rolecheck` returning 0 matches across 1,963 files: the hard
// part (mined, provenance-carrying per-role targets) existed, but nobody owned the verb. This is
// the verb. Every future arm self-checks here before the owner ever listens.
//
// WHAT IT IS NOT. It is not a quality verdict and must never be treated as one. Its thresholds are
// percentiles of the owner's own reference clips, so roughly a quarter of those very clips would
// miss any given `atLeast:25` check. Research 134 measured what happens when a screen is mistaken
// for the bar — the ring gate rejects 22% of the owner's own Splice leads — and research 131 §2.1
// found every "cleanliness" metric voting AGAINST the owner's winners. rolecheck answers exactly
// one question: "did this clip land inside the reference band on the axes measured to matter for
// this role, and if not, which knob moves it?"
//
// Targets live in presets/role-targets.json, regenerated by scripts/build-role-targets.mjs.
// Roughness is deliberately absent: research 123 and 131 §4 both concluded it has no valid
// ABSOLUTE threshold, so it can never be a per-clip screen — only a pair-relative diagnostic
// (`beat lint --roughness-baseline`).

import { existsSync, readFileSync, statSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { featuresForAudioFile, type FeatureVector, type FeatureKey } from './features.js'

export class BeatRoleCheckError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'BeatRoleCheckError'
  }
}

/** presets/role-targets.json, resolved from this module (works from dist/ and from src/). */
export const ROLE_TARGETS_PATH = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'presets', 'role-targets.json')

export interface RoleTargetDistribution {
  n: number
  p10: number
  p25: number
  median: number
  p75: number
  p90: number
}

export interface RoleTargetCheck {
  feature: string
  bound: 'atLeast' | 'atMost' | 'band'
  min?: number
  max?: number
  /** direction-specific fix for a two-sided band; `fix` covers the LOW side, this the HIGH side */
  fixHigh?: string
  /** the check only means what it says on loudness-normalized audio (truePeak, crest) */
  assumesNormalized?: boolean
  minFrom?: 'doc' | 'refPercentile'
  maxFrom?: 'doc' | 'refPercentile'
  refPercentile?: Record<string, unknown>
  docTarget?: { min?: number; max?: number; source?: string }
  ref: RoleTargetDistribution
  lever: string
  source: string
  fix: string
}

export interface RoleVerdictSpec {
  maxMisses: number
  refPassRate: number
  refMissCounts: { min: number; p25: number; median: number; p75: number; max: number }
  note: string
}

export interface RoleTargets {
  version: number
  generatedAt: string
  generator: string
  note: string
  provenance: {
    log: string
    refPool: string
    refClipsTotal: number
    extractor: string
    docs: string[]
    caveats: string[]
  }
  roles: Record<string, {
    refClips: number
    verdict: RoleVerdictSpec
    refLufs: RoleTargetDistribution | null
    checks: RoleTargetCheck[]
    refDistribution: Record<string, RoleTargetDistribution>
  }>
}

export interface RoleCheckRow {
  feature: string
  measured: number
  min?: number
  max?: number
  /** ref median for this feature+role — "what a winning reference clip typically does" */
  refMedian: number
  verdict: 'pass' | 'miss' | 'advisory'
  /** which side of the target the miss is on ('low' = below min, 'high' = above max) */
  side?: 'low' | 'high'
  /** how far outside the target, in units of the ref p25..p75 spread (0 = right on the bound) */
  severity: number
  lever: string
  source: string
  fix: string
  /** why this row is advisory rather than counted (level-dependent check on un-normalized audio) */
  advisoryReason?: string
}

export interface RoleCheckResult {
  audioPath: string
  role: string
  verdict: 'pass' | 'fail'
  passed: number
  missed: number
  /** rows excluded from the verdict because they cannot mean what they say on this audio */
  advisory: number
  /** the miss budget this role's own reference clips set, and the share of them that clear it */
  maxMisses: number
  refPassRate: number
  /** set when the audio does not look like the role asked for — the verdict is withheld */
  applicability?: string
  rows: RoleCheckRow[]
  targets: { version: number; generatedAt: string; refPool: string; refClips: number; extractor: string }
}

/** Load and lightly validate the targets file. A missing or malformed file is a loud error with a
 * regenerate hint — never a silent "everything passes". */
export function loadRoleTargets(path: string = ROLE_TARGETS_PATH): RoleTargets {
  if (!existsSync(path)) {
    throw new BeatRoleCheckError(`no role targets at ${path} — regenerate with: node scripts/build-role-targets.mjs`)
  }
  let parsed: RoleTargets
  try {
    parsed = JSON.parse(readFileSync(path, 'utf8')) as RoleTargets
  } catch (err) {
    throw new BeatRoleCheckError(`role targets at ${path} are not valid JSON (${(err as Error).message}) — regenerate with: node scripts/build-role-targets.mjs`)
  }
  if (parsed.roles === undefined || Object.keys(parsed.roles).length === 0) {
    throw new BeatRoleCheckError(`role targets at ${path} carry no roles — regenerate with: node scripts/build-role-targets.mjs`)
  }
  return parsed
}

export const knownRoles = (targets: RoleTargets): string[] => Object.keys(targets.roles).sort()

/** Evaluate one already-measured feature vector against a role's targets. Separated from file IO
 * so callers that already have features (a batch screen, the pilot loop) never decode twice. */
export function rolecheckFeatures(features: FeatureVector, role: string, targets: RoleTargets, audioPath = ''): RoleCheckResult {
  const spec = targets.roles[role]
  if (spec === undefined) {
    throw new BeatRoleCheckError(`no targets for role "${role}" — known roles: ${knownRoles(targets).join(', ')}`)
  }
  // APPLICABILITY. A typo in --role used to produce a confident, fully-formed wrong report: a drum
  // loop checked as a bassline came back "6/10 checks pass" with advice to bass-mono the sub, on a
  // clip whose spectral centroid was 5.6 kHz. The tool has that number in hand, so it should
  // decline rather than guess. Bound generously (the reference p10..p90 widened by 2 octaves) so
  // this only fires on material that is nowhere near the role.
  const centroidRef = spec.refDistribution.centroidLog2
  let applicability: string | undefined
  if (centroidRef !== undefined) {
    const c = features.centroidLog2
    if (Number.isFinite(c) && (c < centroidRef.p10 - 2 || c > centroidRef.p90 + 2)) {
      applicability =
        `this does not look like a ${role}: spectral centroid ${(2 ** c).toFixed(0)} Hz, while ${role} reference clips ` +
        `run ${(2 ** centroidRef.p10).toFixed(0)}-${(2 ** centroidRef.p90).toFixed(0)} Hz. Check --role (known: ${knownRoles(targets).join(', ')}).`
    }
  }

  // NORMALIZATION. truePeakDb and crestDb only mean what they say on audio normalized the way a
  // showdown batch is (131 §1). On a raw stem sitting 10 dB down they read LEVEL, not punch — and
  // the old report failed the clip on them while printing the retraction two lines lower, under
  // "why". Those rows are now marked advisory and excluded from the verdict instead.
  let levelNote: string | undefined
  if (spec.refLufs !== null && Number.isFinite(features.lufs)) {
    const lo = spec.refLufs.p10 - 3
    const hi = spec.refLufs.p90 + 3
    if (features.lufs < lo || features.lufs > hi) {
      levelNote =
        `clip is ${features.lufs.toFixed(1)} LUFS, outside the ${lo.toFixed(1)}..${hi.toFixed(1)} range of the normalized ` +
        `reference batches — this row would read level, not punch. Normalize first (beat score / the batch normalizer) to make it count.`
    }
  }

  const rows: RoleCheckRow[] = []
  for (const check of spec.checks) {
    const measured = features[check.feature as FeatureKey]
    if (typeof measured !== 'number' || !Number.isFinite(measured)) continue
    // Severity in units of the reference IQR: "how far outside the band, measured in the spread
    // the reference clips themselves show". Dimensionless, so misses on dB, %, ms and ratios are
    // comparable and the report can rank them.
    const spread = Math.max(1e-9, check.ref.p75 - check.ref.p25)
    let verdict: 'pass' | 'miss' | 'advisory' = 'pass'
    let side: 'low' | 'high' | undefined
    let severity = 0
    if (check.min !== undefined && measured < check.min) {
      verdict = 'miss'
      side = 'low'
      severity = (check.min - measured) / spread
    } else if (check.max !== undefined && measured > check.max) {
      verdict = 'miss'
      side = 'high'
      severity = (measured - check.max) / spread
    }
    const advisory = verdict === 'miss' && check.assumesNormalized === true && levelNote !== undefined
    if (advisory) verdict = 'advisory'
    const row: RoleCheckRow = {
      feature: check.feature,
      measured,
      refMedian: check.ref.median,
      verdict,
      severity: Math.round(severity * 100) / 100,
      lever: check.lever,
      source: check.source,
      // Direction-aware: `fix` describes the LOW side, `fixHigh` the HIGH side. A two-sided band
      // with one fix string is wrong half the time — it used to tell a clip 5 dB TOO NOISY to add
      // a noise oscillator.
      fix: side === 'high' && check.fixHigh !== undefined ? check.fixHigh : check.fix,
    }
    if (advisory) row.advisoryReason = levelNote
    if (check.min !== undefined) row.min = check.min
    if (check.max !== undefined) row.max = check.max
    if (side !== undefined) row.side = side
    rows.push(row)
  }
  if (rows.length === 0) {
    throw new BeatRoleCheckError(`role "${role}" produced no evaluable checks — the targets file and the feature set disagree; regenerate with: node scripts/build-role-targets.mjs`)
  }
  const missed = rows.filter((r) => r.verdict === 'miss').length
  const advisoryCount = rows.filter((r) => r.verdict === 'advisory').length
  // THE VERDICT IS A MISS BUDGET, NOT AN AND. An AND over 8-11 percentile checks rejected 98.7% of
  // the very reference clips the targets were mined from (a 2026-07-26 usability pilot measured
  // 157/159), because per-check miss rates compound: 0.75^10 = 5.6%. `maxMisses` is calibrated on
  // this role's own reference pool so ~75% of the owner's winning references clear the bar; the
  // realized rate travels with the result so the number is never left implicit again.
  const maxMisses = spec.verdict?.maxMisses ?? 0
  const result: RoleCheckResult = {
    audioPath,
    role,
    verdict: missed <= maxMisses ? 'pass' : 'fail',
    passed: rows.length - missed - advisoryCount,
    missed,
    advisory: advisoryCount,
    maxMisses,
    refPassRate: spec.verdict?.refPassRate ?? 0,
    rows,
    targets: {
      version: targets.version,
      generatedAt: targets.generatedAt,
      refPool: targets.provenance.refPool,
      refClips: spec.refClips,
      extractor: targets.provenance.extractor,
    },
  }
  if (applicability !== undefined) result.applicability = applicability
  return result
}

/** Measure one render and check it against a role's targets. */
export function rolecheckFile(audioPath: string, role: string, targets: RoleTargets): RoleCheckResult {
  if (!existsSync(audioPath)) throw new BeatRoleCheckError(`no audio file at ${audioPath}`)
  if (statSync(audioPath).isDirectory()) {
    throw new BeatRoleCheckError(
      `${audioPath} is a directory — rolecheck screens ONE rendered WAV at a time. For a whole batch: ` +
        `for f in ${audioPath}/*.wav; do beat rolecheck "$f" --role ${role}; done`,
    )
  }
  const features = featuresForAudioFile(audioPath)
  if (features === null) throw new BeatRoleCheckError(`could not decode ${audioPath} — rolecheck needs a readable WAV`)
  return rolecheckFeatures(features, role, targets, audioPath)
}

const fmt = (x: number) => (Math.abs(x) >= 100 ? x.toFixed(0) : Math.abs(x) >= 1 ? x.toFixed(2) : x.toFixed(3))

function targetText(row: RoleCheckRow): string {
  if (row.min !== undefined && row.max !== undefined) return `${fmt(row.min)}..${fmt(row.max)}`
  if (row.min !== undefined) return `>= ${fmt(row.min)}`
  if (row.max !== undefined) return `<= ${fmt(row.max)}`
  return '-'
}

/** Human-readable report: the per-feature table first (so a passing clip is one glance), then one
 * NAMED FIX block per miss, worst first. */
export function formatRoleCheck(r: RoleCheckResult): string {
  const out: string[] = []
  const name = r.audioPath === '' ? '(features)' : r.audioPath
  out.push(`rolecheck ${name} as ${r.role}: ${r.verdict.toUpperCase()} — ${r.missed} miss${r.missed === 1 ? '' : 'es'} (bar: at most ${r.maxMisses}), ${r.passed}/${r.rows.length} checks pass`)
  out.push(`targets v${r.targets.version} from ${r.targets.refClips} ${r.targets.refPool} reference clips (${r.targets.generatedAt.slice(0, 10)}); ${(r.refPassRate * 100).toFixed(0)}% of those references clear this same bar`)
  if (r.applicability !== undefined) {
    out.push('')
    out.push(`  !! ${r.applicability}`)
    out.push('  The rows below are still printed, but read them knowing the targets are for a different kind of material.')
  }
  out.push('')
  const w = Math.max(...r.rows.map((x) => x.feature.length), 7)
  out.push(`  ${'feature'.padEnd(w)}  ${'measured'.padStart(10)}  ${'target'.padStart(16)}  ${'ref med'.padStart(9)}  verdict`)
  for (const row of r.rows) {
    const mark = row.verdict === 'pass' ? 'ok' : row.verdict === 'advisory' ? `(advisory ${row.side === 'low' ? 'low' : 'high'})` : `MISS ${row.side === 'low' ? 'low' : 'high'}`
    out.push(`  ${row.feature.padEnd(w)}  ${fmt(row.measured).padStart(10)}  ${targetText(row).padStart(16)}  ${fmt(row.refMedian).padStart(9)}  ${mark}`)
  }
  const advisories = r.rows.filter((x) => x.verdict === 'advisory')
  if (advisories.length > 0) {
    out.push('')
    out.push(`${advisories.length} row${advisories.length === 1 ? '' : 's'} NOT counted — ${advisories[0]!.advisoryReason}`)
    out.push(`  (${advisories.map((a) => a.feature).join(', ')})`)
  }
  const misses = r.rows.filter((x) => x.verdict === 'miss').sort((a, b) => b.severity - a.severity)
  if (misses.length === 0) {
    out.push('')
    out.push('every measured axis is inside the reference band for this role. This is a SCREEN, not a')
    out.push('quality verdict — no feature here hears harmony, groove or pocket (131 §8), and it does')
    out.push('NOT rank clips: use `beat rank` / the taste critic for that.')
    return out.join('\n')
  }
  out.push('')
  out.push(`${misses.length} miss${misses.length === 1 ? '' : 'es'}, worst first (severity = distance outside the band in reference-IQR units).`)
  out.push(`The role's own reference clips miss several of these too — the BUDGET is the verdict, this list is the diagnosis:`)
  for (const m of misses) {
    out.push('')
    out.push(`  ${m.feature} — measured ${fmt(m.measured)}, wants ${targetText(m)} (ref median ${fmt(m.refMedian)}), severity ${m.severity.toFixed(2)}`)
    out.push(`    lever: ${m.lever}`)
    const fixLines = wrap(m.fix, 72)
    out.push(`    fix:   ${fixLines[0]}`)
    for (const line of fixLines.slice(1)) out.push(`           ${line}`)
    out.push(`    why:   ${m.source}`)
  }
  return out.join('\n')
}

function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/)
  const lines: string[] = []
  let line = ''
  for (const word of words) {
    if (line.length > 0 && line.length + 1 + word.length > width) {
      lines.push(line)
      line = word
    } else line = line.length === 0 ? word : `${line} ${word}`
  }
  if (line.length > 0) lines.push(line)
  return lines
}

/** Resolve the targets path a CLI/MCP caller asked for, defaulting to the shipped presets file. */
export const resolveRoleTargetsPath = (explicit?: string) => (explicit === undefined ? ROLE_TARGETS_PATH : resolve(explicit))

/** Convenience for callers that only have a directory of renders. */
export const roleTargetsInRepo = (repoRoot: string) => join(repoRoot, 'presets', 'role-targets.json')
