// `beat rolecheck <wav> --role <role>` — the pre-batch pass/fail screen (research 138 §3-B2,
// 140 D26). One clip, one role, one verdict per measured axis, and for every MISS the specific
// dotbeat parameter to change.
//
// WHY THIS EXISTS. Research 138 states the design rule the program has never had a way to obey:
// "every arm's clips pass their feature gates BEFORE entering a batch (never spend owner ratings
// on a clip that missed its own targets)" — owner rating time is the scarcest resource in the
// whole program. Doc 140 found `rg rolecheck` returning 0 matches across 1,963 files: the hard
// part (mined, provenance-carrying per-role targets) existed, but nobody owned the verb. This is
// the verb. Every future arm self-checks here before the owner ever listens.
//
// WHAT IT IS NOT. It is not a quality verdict and must never be treated as one. Its thresholds are
// percentiles of the owner's own reference clips, so roughly a quarter of those very clips would
// miss any given `atLeast:25` check. Research 134 measured what happens when a screen is mistaken
// for the bar — the ring gate rejects 22% of the owner's own Splice leads — and research 131 §2.1
// found every "cleanliness" metric voting AGAINST the owner's winners. rolecheck answers exactly
// one question: "did this clip land inside the reference band on the axes measured to matter for
// this role, and if not, which knob moves it?"
//
// Targets live in presets/role-targets.json, regenerated by scripts/build-role-targets.mjs.
// Roughness is deliberately absent: research 123 and 131 §4 both concluded it has no valid
// ABSOLUTE threshold, so it can never be a per-clip screen — only a pair-relative diagnostic
// (`beat lint --roughness-baseline`).

import { existsSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { featuresForAudioFile, type FeatureVector, type FeatureKey } from './features.js'

export class BeatRoleCheckError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'BeatRoleCheckError'
  }
}

/** presets/role-targets.json, resolved from this module (works from dist/ and from src/). */
export const ROLE_TARGETS_PATH = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'presets', 'role-targets.json')

export interface RoleTargetDistribution {
  n: number
  p10: number
  p25: number
  median: number
  p75: number
  p90: number
}

export interface RoleTargetCheck {
  feature: string
  bound: 'atLeast' | 'atMost' | 'band'
  min?: number
  max?: number
  minFrom?: 'doc' | 'refPercentile'
  maxFrom?: 'doc' | 'refPercentile'
  refPercentile?: Record<string, unknown>
  docTarget?: { min?: number; max?: number; source?: string }
  ref: RoleTargetDistribution
  lever: string
  source: string
  fix: string
}

export interface RoleTargets {
  version: number
  generatedAt: string
  generator: string
  note: string
  provenance: {
    log: string
    refPool: string
    refClipsTotal: number
    extractor: string
    docs: string[]
    caveats: string[]
  }
  roles: Record<string, { refClips: number; checks: RoleTargetCheck[]; refDistribution: Record<string, RoleTargetDistribution> }>
}

export interface RoleCheckRow {
  feature: string
  measured: number
  min?: number
  max?: number
  /** ref median for this feature+role — "what a winning reference clip typically does" */
  refMedian: number
  verdict: 'pass' | 'miss'
  /** which side of the target the miss is on ('low' = below min, 'high' = above max) */
  side?: 'low' | 'high'
  /** how far outside the target, in units of the ref p25..p75 spread (0 = right on the bound) */
  severity: number
  lever: string
  source: string
  fix: string
}

export interface RoleCheckResult {
  audioPath: string
  role: string
  verdict: 'pass' | 'fail'
  passed: number
  missed: number
  rows: RoleCheckRow[]
  targets: { version: number; generatedAt: string; refPool: string; refClips: number; extractor: string }
}

/** Load and lightly validate the targets file. A missing or malformed file is a loud error with a
 * regenerate hint — never a silent "everything passes". */
export function loadRoleTargets(path: string = ROLE_TARGETS_PATH): RoleTargets {
  if (!existsSync(path)) {
    throw new BeatRoleCheckError(`no role targets at ${path} — regenerate with: node scripts/build-role-targets.mjs`)
  }
  let parsed: RoleTargets
  try {
    parsed = JSON.parse(readFileSync(path, 'utf8')) as RoleTargets
  } catch (err) {
    throw new BeatRoleCheckError(`role targets at ${path} are not valid JSON (${(err as Error).message}) — regenerate with: node scripts/build-role-targets.mjs`)
  }
  if (parsed.roles === undefined || Object.keys(parsed.roles).length === 0) {
    throw new BeatRoleCheckError(`role targets at ${path} carry no roles — regenerate with: node scripts/build-role-targets.mjs`)
  }
  return parsed
}

export const knownRoles = (targets: RoleTargets): string[] => Object.keys(targets.roles).sort()

/** Evaluate one already-measured feature vector against a role's targets. Separated from file IO
 * so callers that already have features (a batch screen, the pilot loop) never decode twice. */
export function rolecheckFeatures(features: FeatureVector, role: string, targets: RoleTargets, audioPath = ''): RoleCheckResult {
  const spec = targets.roles[role]
  if (spec === undefined) {
    throw new BeatRoleCheckError(`no targets for role "${role}" — known roles: ${knownRoles(targets).join(', ')}`)
  }
  const rows: RoleCheckRow[] = []
  for (const check of spec.checks) {
    const measured = features[check.feature as FeatureKey]
    if (typeof measured !== 'number' || !Number.isFinite(measured)) continue
    // Severity in units of the reference IQR: "how far outside the band, measured in the spread
    // the reference clips themselves show". Dimensionless, so misses on dB, %, ms and ratios are
    // comparable and the report can rank them.
    const spread = Math.max(1e-9, check.ref.p75 - check.ref.p25)
    let verdict: 'pass' | 'miss' = 'pass'
    let side: 'low' | 'high' | undefined
    let severity = 0
    if (check.min !== undefined && measured < check.min) {
      verdict = 'miss'
      side = 'low'
      severity = (check.min - measured) / spread
    } else if (check.max !== undefined && measured > check.max) {
      verdict = 'miss'
      side = 'high'
      severity = (measured - check.max) / spread
    }
    const row: RoleCheckRow = {
      feature: check.feature,
      measured,
      refMedian: check.ref.median,
      verdict,
      severity: Math.round(severity * 100) / 100,
      lever: check.lever,
      source: check.source,
      fix: check.fix,
    }
    if (check.min !== undefined) row.min = check.min
    if (check.max !== undefined) row.max = check.max
    if (side !== undefined) row.side = side
    rows.push(row)
  }
  if (rows.length === 0) {
    throw new BeatRoleCheckError(`role "${role}" produced no evaluable checks — the targets file and the feature set disagree; regenerate with: node scripts/build-role-targets.mjs`)
  }
  const missed = rows.filter((r) => r.verdict === 'miss').length
  return {
    audioPath,
    role,
    verdict: missed === 0 ? 'pass' : 'fail',
    passed: rows.length - missed,
    missed,
    rows,
    targets: {
      version: targets.version,
      generatedAt: targets.generatedAt,
      refPool: targets.provenance.refPool,
      refClips: spec.refClips,
      extractor: targets.provenance.extractor,
    },
  }
}

/** Measure one render and check it against a role's targets. */
export function rolecheckFile(audioPath: string, role: string, targets: RoleTargets): RoleCheckResult {
  if (!existsSync(audioPath)) throw new BeatRoleCheckError(`no audio file at ${audioPath}`)
  const features = featuresForAudioFile(audioPath)
  if (features === null) throw new BeatRoleCheckError(`could not decode ${audioPath} — rolecheck needs a readable WAV`)
  return rolecheckFeatures(features, role, targets, audioPath)
}

const fmt = (x: number) => (Math.abs(x) >= 100 ? x.toFixed(0) : Math.abs(x) >= 1 ? x.toFixed(2) : x.toFixed(3))

function targetText(row: RoleCheckRow): string {
  if (row.min !== undefined && row.max !== undefined) return `${fmt(row.min)}..${fmt(row.max)}`
  if (row.min !== undefined) return `>= ${fmt(row.min)}`
  if (row.max !== undefined) return `<= ${fmt(row.max)}`
  return '-'
}

/** Human-readable report: the per-feature table first (so a passing clip is one glance), then one
 * NAMED FIX block per miss, worst first. */
export function formatRoleCheck(r: RoleCheckResult): string {
  const out: string[] = []
  const name = r.audioPath === '' ? '(features)' : r.audioPath
  out.push(`rolecheck ${name} as ${r.role}: ${r.verdict.toUpperCase()} — ${r.passed}/${r.rows.length} checks pass`)
  out.push(`targets v${r.targets.version} from ${r.targets.refClips} ${r.targets.refPool} reference clips (${r.targets.generatedAt.slice(0, 10)})`)
  out.push('')
  const w = Math.max(...r.rows.map((x) => x.feature.length), 7)
  out.push(`  ${'feature'.padEnd(w)}  ${'measured'.padStart(10)}  ${'target'.padStart(16)}  ${'ref med'.padStart(9)}  verdict`)
  for (const row of r.rows) {
    const mark = row.verdict === 'pass' ? 'ok' : `MISS ${row.side === 'low' ? 'low' : 'high'}`
    out.push(`  ${row.feature.padEnd(w)}  ${fmt(row.measured).padStart(10)}  ${targetText(row).padStart(16)}  ${fmt(row.refMedian).padStart(9)}  ${mark}`)
  }
  const misses = r.rows.filter((x) => x.verdict === 'miss').sort((a, b) => b.severity - a.severity)
  if (misses.length === 0) {
    out.push('')
    out.push('every measured axis is inside the reference band for this role. This is a SCREEN, not a')
    out.push('quality verdict — no feature here hears harmony, groove or pocket (131 §8).')
    return out.join('\n')
  }
  out.push('')
  out.push(`${misses.length} miss${misses.length === 1 ? '' : 'es'}, worst first (severity = distance outside the band in reference-IQR units):`)
  for (const m of misses) {
    out.push('')
    out.push(`  ${m.feature} — measured ${fmt(m.measured)}, wants ${targetText(m)} (ref median ${fmt(m.refMedian)}), severity ${m.severity.toFixed(2)}`)
    out.push(`    lever: ${m.lever}`)
    const fixLines = wrap(m.fix, 72)
    out.push(`    fix:   ${fixLines[0]}`)
    for (const line of fixLines.slice(1)) out.push(`           ${line}`)
    out.push(`    why:   ${m.source}`)
  }
  return out.join('\n')
}

function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/)
  const lines: string[] = []
  let line = ''
  for (const word of words) {
    if (line.length > 0 && line.length + 1 + word.length > width) {
      lines.push(line)
      line = word
    } else line = line.length === 0 ? word : `${line} ${word}`
  }
  if (line.length > 0) lines.push(line)
  return lines
}

/** Resolve the targets path a CLI/MCP caller asked for, defaulting to the shipped presets file. */
export const resolveRoleTargetsPath = (explicit?: string) => (explicit === undefined ? ROLE_TARGETS_PATH : resolve(explicit))

/** Convenience for callers that only have a directory of renders. */
export const roleTargetsInRepo = (repoRoot: string) => join(repoRoot, 'presets', 'role-targets.json')
