export * from './document.js'
export * from './format.js'
export { automationShapePoints, AUTOMATION_SHAPES, AutomationShapeError, type AutomationShape, type AutomationShapeOptions, type AutomationShapePoint } from './automation-shape.js'
export { parse, BeatParseError } from './parse.js'
export { serialize } from './serialize.js'
export { unplacedContentTracks, unplacedContentWarning, type UnplacedContentTrack } from './coverage.js'
export {
  sandboxPayloadToBeatDocument,
  beatDocumentToPartialTracks,
  DELIBERATELY_UNMODELED,
  type ExternalSandboxPayload,
  type ExternalTrack,
  type ExternalClipAutomation,
  type ConversionReport,
  type PartialTrack,
} from './convert.js'
export { diffDocuments, formatDiff, type DiffEntry } from './diff.js'
export {
  setValue,
  addNote,
  removeNote,
  duplicateNotes,
  addHit,
  removeHit,
  quantizeNotes,
  addTrack,
  removeTrack,
  initDocument,
  addGroup,
  removeGroup,
  renameGroup,
  setGroupColor,
  setGroupTracks,
  saveClip,
  loadClip,
  setScene,
  placeClip,
  unplaceClip,
  renameScene,
  setSong,
  songMove,
  nextSceneId,
  songInsert,
  insertScene,
  setMediaSample,
  setLaneSample,
  clearLegacyLaneSamples,
  addAutomationPoint,
  moveAutomationPoint,
  removeAutomationPoint,
  setAutomationPoint,
  applyAutomationShape,
  addEffect,
  removeEffect,
  moveEffect,
  setEffectEnabled,
  materializeLanes,
  addLane,
  removeLane,
  moveLane,
  setLaneBacking,
  setLaneParam,
  setLaneParamPath,
  setClipLoop,
  setClipSignature,
  addAudioClip,
  setClipAudioRegion,
  splitAudioClip,
  duplicateClip,
  BeatEditError,
  type QuantizeOptions,
  type DuplicateNotesOptions,
  type BeatSlotsInput,
} from './edit.js'
export { humanize, BeatHumanizeError, type HumanizeOptions } from './humanize.js'
export { moebiusEase, warpStep, unwarpStep } from './groove.js'
export { chanceFires } from './chance.js'
export {
  transposeNotes,
  timeScaleNotes,
  fitToScaleNotes,
  invertNotes,
  reverseNotes,
  legatoNotes,
  consolidateRatchet,
  ratchetSlots,
  SCALES,
  SCALE_NAMES,
  BeatPitchTimeError,
  type NoteScopeOptions,
} from './pitchtime.js'
export { describeDocument } from './inspect.js'
export {
  parsePresetLibrary,
  applyPreset,
  formatPresetList,
  filterPresetsByCategory,
  BeatPresetError,
  type BeatPreset,
  type PresetCategory,
  PRESET_CATEGORIES,
  SYNTH_PRESET_CATEGORIES,
  DRUM_PRESET_CATEGORIES,
} from './preset.js'
export {
  parseDrumKitLibrary,
  applyDrumKit,
  formatDrumKitList,
  BeatDrumKitError,
  type BeatDrumKit,
} from './drumkit.js'
export {
  parseMacroLibrary,
  resolveMacro,
  applyMacro,
  formatMacroList,
  inverseResolveTarget,
  BeatMacroError,
  type BeatMacro,
  type MacroTarget,
  type MacroCurve,
  type MacroCategory,
  MACRO_CATEGORIES,
} from './macro.js'
export {
  parseSelection,
  serializeSelection,
  validateSelection,
  selectionToNoteIds,
  selectionToVaryScope,
  BeatSelectionError,
  type BeatSelection,
  type SelectionLane,
  type SelectionNote,
  type VaryScope,
} from './selection.js'
