// Preset retargeting (docs/preset-retargeting.md): take a human-designed known-good preset and
// LOCALLY optimize it toward the scalar feature targets research/131 measured, inside a trust
// region, without breaking what the preset already got right. Public surface.
export {
  RETARGET_REF_LUFS,
  RETARGET_FEATURE_KEYS,
  RETARGET_BANDS,
  computeRetargetFeatures,
  normalizeToRefLufs,
  magnitudeStft,
  spectralFlux,
  spectralFlatnessDb,
  spectralSlopeDbPerOct,
  bandCrestDb,
  fineEnvelope,
  onsetStats,
  envelopeStats,
  widthMeanDb,
  quantile,
  median,
  type RetargetFeatures,
  type RetargetFeatureKey,
  type FluxResult,
  type OnsetStats,
} from './features.js'
export {
  RETARGET_ROLES,
  RETARGET_FEATURE_SCALES,
  targetProfileFor,
  targetMiss,
  targetSatisfied,
  describeTarget,
  profileKeys,
  featureValue,
  type TargetKind,
  type FeatureTarget,
  type RoleTargetProfile,
} from './targets.js'
export {
  RETARGET_LOSS_VERSION,
  GAP_POWER,
  MISS_CAP,
  PRESERVE_FREE_BAND,
  W_REGRESS,
  W_PRESERVE,
  W_DRIFT,
  retargetLoss,
  powerMean,
  formatLossLine,
  type AxisDetail,
  type RetargetLossDetail,
  type RetargetLossOptions,
} from './loss.js'
export {
  retargetSpace,
  denormalize,
  normalize,
  fieldDefault,
  presetGenome,
  trustBounds,
  genomeToParams,
  roundParam,
  paramDiff,
  type RetargetParamDef,
  type ParamMove,
} from './space.js'
export {
  runRetarget,
  formatRetargetReport,
  presetZ,
  zToGenome,
  RetargetError,
  type RetargetOptions,
  type RetargetResult,
  type RetargetRenderer,
  type RetargetPoint,
  type DecodedAudio,
} from './harness.js'
